---
# failed after ansible 2.10 upgrade: https://github.com/dw/mitogen/blob/master/tests/ansible/integration/action/fixup_perms2__copy.yml#L29
# TEST=perms-ansible-2-10 ANSIBLE_VERSION=2.10.0 USE_DOCKER=true CONTAINER_IMAGE=ubuntu:18.04 make run-test

#
# copy module (no mode).
#

- name: "Copy files (no mode)"
  copy:
    content: ""
    dest: /tmp/copy-no-mode

- stat: path=/tmp/copy-no-mode
  register: out
- assert:
    that:
    -  out.stat.mode in ("0644", "0666")

#
# copy module (explicit mode).
#

- name: "Copy files from content: arg"
  copy:
    content: ""
    mode: 0400
    dest: /tmp/copy-with-mode

- stat: path=/tmp/copy-with-mode
  register: out
- assert:
    that:
    -  out.stat.mode == "0400"

#
# copy module (existing disk files, no mode).
#

- file:
    path: /tmp/weird-mode.out
    state: absent

- name: Create local test file.
  delegate_to: localhost
  copy:
    content: "weird mode"
    dest: "/tmp/weird-mode"
    mode: "1462"

- copy:
    src: "/tmp/weird-mode"
    dest: "/tmp/weird-mode.out"

- stat:
    path: "/tmp/weird-mode.out"
  register: out
- assert:
    that:
    - out.stat.mode in ("0644", "0666")

#
# copy module (existing disk files, preserve mode).
#

- copy:
    src: "/tmp/weird-mode"
    dest: "/tmp/weird-mode"
    mode: preserve

- stat:
    path: "/tmp/weird-mode"
  register: out
- assert:
    that:
    - out.stat.mode == "1462"

#
# copy module (existing disk files, explicit mode).
#

- copy:
    src: "/tmp/weird-mode"
    dest: "/tmp/weird-mode"
    mode: "1461"

- stat:
    path: "/tmp/weird-mode"
  register: out

- assert:
    that:
    - out.stat.mode == "1461"

- file:
    state: absent
    path: "{{item}}"
  with_items:
  - /tmp/weird-mode
  - /tmp/weird-mode.out
  - /tmp/copy-no-mode
  - /tmp/copy-no-mode.out
  - /tmp/copy-with-mode
  - /tmp/copy-with-mode.out

# end of cleaning out files
