---
# https://github.com/dw/mitogen/issues/655
# TEST=wait_for_connection CONTAINER_IMAGE=ubuntu:18.04 make run-test

# to repro the issue, will create /var/run/reboot-required
- name: create test file
  file:
    path: /var/run/reboot-required
    state: touch

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  when: reboot_required.stat.exists == True

- name: Wait 300 seconds for server to become available
  wait_for_connection:
    delay: 30
    timeout: 300
  when: reboot_required.stat.exists == True
