---
# place for small bugs/generic fixes
# validates:
# https://github.com/dw/mitogen/issues/716

### TEST 716 --> TEST=misc CONTAINER_IMAGE=centos:7 ANSIBLE_VERSION=2.4.2 PYTHON_VERSION=2 make run-test
- name: T00.00 Prepare file
  lineinfile:
    path: "/tmp/fileC"
    line: "test"
    create: yes

- name: T00.01 Fetch file
  fetch:
    src: "/tmp/fileC"
    dest: "/tmp/fileC"
### END TEST 716
