---
# validates patch https://github.com/dw/mitogen/pull/658 via `make complex-args-test`
# if USE_DOCKER is set, runs tests on a newly created container instead of plain localhost

- name: set up test container and run tests inside it
  block:
    - name: install deps
      pip:
        name: docker
      environment:
        https_proxy: "{{ lookup('env', 'https_proxy')|default('') }}"
        no_proxy: "{{ lookup('env', 'no_proxy')|default('') }}"
        PATH: "{{ lookup('env', 'PATH') }}"

    - name: create test container
      docker_container:
        name: testMitogen
        image: "{{ container_image }}"
        state: started
        recreate: yes
        command: sleep infinity

    - name: install python into container for mitogen
      shell: docker exec testMitogen bash -c "yum install -y python3 && ln -s /usr/bin/python3 /usr/bin/python"
      environment:
        PATH: "{{ lookup('env', 'PATH') }}"
      when: "'centos' in container_image"

    - name: add container to inventory
      add_host:
        name: testMitogen
        ansible_connection: docker
        ansible_user: root
      changed_when: false

    - name: run tests
      delegate_to: testMitogen
      import_tasks: tests.yml
  when: use_docker.lower() == 'true'

- name: run tests on localhost
  import_tasks: tests.yml
  when: use_docker.lower() == 'false'
