---
# validates patch https://github.com/dw/mitogen/pull/658 via `make complex-args-test`
# if USE_DOCKER is set, runs tests on a newly created container instead of plain localhost

- name: set up test container and run tests inside it
  block:
    - name: install deps
      pip:
        name: docker
      environment:
        https_proxy: "{{ lookup('env', 'https_proxy')|default('') }}"
        no_proxy: "{{ lookup('env', 'no_proxy')|default('') }}"
        PATH: "{{ lookup('env', 'PATH') }}"

    - name: create test container {{ container_image }}
      docker_container:
        name: testMitogen
        image: "{{ container_image }}"
        state: started
        recreate: yes
        command: sleep infinity

    - name: get distro info
      set_fact:
        distro: '{{ ansible_distribution | default("unknown") | lower }}'

    - name: set python install cmd based on distro
      block:
        - name: set python install cmd for rhel-based distros
          set_fact:
            # centos8 doesn't have the python target
            python_install_cmd: yum install -y python || (yum install -y python3 && ln -s /usr/bin/python3 /usr/bin/python)
          when: "'centos' in container_image"

        - name: set python install cmd for rhel-based distros
          set_fact:
            python_install_cmd: apt-get install -y python
          when: "'ubuntu' in container_image"

    - name: install python into container for mitogen
      shell: docker exec testMitogen bash -c "{{ python_install_cmd }}"
      environment:
        PATH: "{{ lookup('env', 'PATH') }}"

    - name: add container to inventory
      add_host:
        name: testMitogen
        ansible_connection: docker
        ansible_user: root
      changed_when: false

    - name: run tests
      delegate_to: testMitogen
      import_tasks: tests.yml
  when: use_docker.lower() == 'true'

- name: run tests on localhost
  import_tasks: tests.yml
  when: use_docker.lower() == 'false'
