---
- name: set up test container and run tests inside it
  block:
    - name: install deps
      pip:
        name: docker
        executable: pip3

    - name: create test container {{ container_image }}
      docker_container:
        name: testMitogen
        image: "{{ container_image }}"
        state: started
        recreate: yes
        command: sleep infinity
      vars:
        # Mac Catalina does weird stuff to /usr/bin/python
        # (`which python` returns /usr/bin/python which is python3 when you call `python` only but `python2` otherwise)
        # TODO: don't force this to be python3?
        ansible_python_interpreter: /usr/bin/python3

    - name: set python install cmd based on distro (example -- ubuntu 20.04 container has no python by default)
      block:
        - name: default to not installing any python
          set_fact:
            python_install_cmd: echo 'Mocking python install'

        - name: set python install cmd for rhel-based distros
          set_fact:
            # centos8 doesn't have the python target, and centos6 doesn't have python3 (needs rh-python3)
            python_install_cmd: yum install -y python || (yum install -y python3 && ln -s /usr/bin/python3 /usr/bin/python)
          when: "'centos' in container_image and not 'centos:8' in container_image"

        - name: set python install cmd for ubuntu distros
          set_fact:
            # ubuntu 14.04 can no longer hit the ubuntu update endpoint *facepalm* and installing python3 and symlinking breaks mitogen
            python_install_cmd: (apt-get install -y python || (apt-get update && apt-get install -y python3 ca-certificates && ln -s /usr/bin/python3 /usr/bin/python))
          when: "'ubuntu' in container_image"

    - name: install python into container for mitogen
      shell: docker exec testMitogen sh -c "{{ python_install_cmd }}"
      environment:
        PATH: "{{ lookup('env', 'PATH') }}"

    - name: add container to inventory
      add_host:
        name: testMitogen
        ansible_connection: docker
        ansible_user: root
      changed_when: false

    - name: run tests
      delegate_to: testMitogen
      import_tasks: "{{ role_path }}/{{ test_dir }}/tests.yml"
  when: use_docker.lower() == 'true'

- name: run tests on localhost
  import_tasks: "{{ role_path }}/{{ test_dir }}/tests.yml"
  when: use_docker.lower() == 'false'
