# failed after ansible 2.10 upgrade: https://github.com/dw/mitogen/blob/master/tests/ansible/integration/strategy/_mixed_mitogen_vanilla.yml#L25
# PLAYBOOK=mixed-mitogen-vanilla-ansible-2-10 ANSIBLE_VERSION=2.10.0 USE_DOCKER=false make run-test
# issue #294: ensure running mixed vanilla/Mitogen succeeds.

- name: integration/strategy/_mixed_vanilla_mitogen.yml (linear)
  hosts: node
  any_errors_fatal: true
  strategy: linear
  tasks:
    - custom_python_detect_environment:
      register: out
    - assert:
        that: not out.mitogen_loaded

    - determine_strategy:
    - assert:
        that: strategy == 'ansible.plugins.strategy.linear.StrategyModule'

- name: integration/strategy/_mixed_vanilla_mitogen.yml (mitogen_linear)
  hosts: node
  any_errors_fatal: true
  strategy: mitogen_linear
  tasks:
    - custom_python_detect_environment:
      register: out
    - assert:
        that: out.mitogen_loaded

    - determine_strategy:
    - assert:
        that: strategy == 'ansible.plugins.strategy.mitogen_linear.StrategyModule'


- name: integration/strategy/_mixed_vanilla_mitogen.yml (linear)
  hosts: node
  any_errors_fatal: true
  strategy: linear
  tasks:
    - custom_python_detect_environment:
      register: out
    - assert:
        that: not out.mitogen_loaded

    - determine_strategy:
    - assert:
        that: strategy == 'ansible.plugins.strategy.linear.StrategyModule'
