---
# Provides the setup for collections tests not from the top-level playbook

- hosts: node
  gather_facts: false
  vars:
    foo: "fooFooFOO"
    # Test having the filter plugin loaded early
    blip: "{{ foo |alikins.collection_inspect.collection_inspect }}"
  roles:
  - run_test
