---
# Provides the setup for collections tests not from the top-level playbook
# see collections.yml in same dir for another example
# TEST=collections PLAYBOOK=collections-roles ANSIBLE_VERSION=2.10.0 make run-test

- hosts: node
  gather_facts: false
  vars:
    foo: "fooFooFOO"
    # Test having the filter plugin loaded early
    blip: "{{ foo |alikins.collection_inspect.collection_inspect }}"
    dummy: "dummy"
    loader_info: "{{ dummy|alikins.collection_inspect.collection_inspect }}"
  tags:
    - a_become_play_tag
  roles:
  - run_test
