# failed after ansible 2.10 upgrade: https://github.com/dw/mitogen/blob/master/tests/ansible/integration/strategy/_mixed_mitogen_vanilla.yml#L25
# PLAYBOOK=mixed-mitogen-vanilla-ansible-2-10 ANSIBLE_VERSION=2.10.0 USE_DOCKER=false make run-test

- name: integration/strategy/mixed_vanilla_mitogen.yml (linear->mitogen->linear)
  hosts: node
  any_errors_fatal: true
  tasks:
    - connection: local
      command: |
        "{{playbook_cmd}}"
        -i "{{playbook_dir}}/../inventory/local"
        -e ansible_ssh_pass={{ansible_ssh_pass}}
        -e ansible_sudo_pass={{ansible_sudo_pass}}
        -e ansible_become_pass={{ansible_sudo_pass}}
        -vvv
        "{{playbook_dir}}/_mixed_mitogen_vanilla.yml"
      args:
        chdir: "{{playbook_dir}}/../"
      register: out

    - connection: local
      command: |
        "{{playbook_cmd}}"
        -i "{{playbook_dir}}/../inventory/local"
        -e ansible_ssh_pass={{ansible_ssh_pass}}
        -e ansible_sudo_pass={{ansible_sudo_pass}}
        -e ansible_become_pass={{ansible_sudo_pass}}
        -vvv
        "{{playbook_dir}}/_mixed_vanilla_mitogen.yml"
      args:
        chdir: "{{playbook_dir}}/../"
      register: out
