---
# TEST=debops CONTAINER_IMAGE=ubuntu:18.04 REBUILD_CONTAINER=false make run-test
# a way to run debops the way Mitogen runs it
# this test will run `debops common` on the desired CONTAINER_IMAGE using Mitogen

- name: call setup to get ansible hostname
  setup:

- name: install pip and debops deps in container
  block:
    - name: install package deps
      package:
        name:
          # for debops
          - build-essential
          - libldap2-dev
          - libsasl2-dev
          - ldap-utils
          - lcov
          - python3-pip
          - python3-dev
          - slapd
          - valgrind
          # specifically to get ansible_interfaces fact, otherwise Ansible fails silently
          - iproute2
      # slapd requires putting in a pw otherwise
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: run resolveconf workaround to install in container
      shell: echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections

    - name: install debops
      pip:
        name: debops[ansible]
        version: 2.1.2
        executable: /usr/bin/pip3
  when: rebuild_container == "true"

- name: blow away any old debops config setup
  file:
    name: /tmp/debops-test
    state: absent

- name: init debops
  shell: debops-init debops-test
  args:
    chdir: /tmp

- name: create debops config file
  copy:
    dest: /tmp/debops-test/.debops.cfg
    content: |
      [ansible defaults]
      strategy_plugins = /mitogen/ansible_mitogen/plugins/strategy
      strategy = mitogen_linear
      # patch bad lookup_plugins location for debops
      lookup_plugins = /usr/local/lib/python3.6/dist-packages/debops/ansible/roles/ansible_plugins/lookup_plugins

- name: create debops vars file
  copy:
    dest: /tmp/debops-test/ansible/inventory/group_vars/debops_all_hosts.yml
    content: |
      # Speed up slow DH generation.
      dhparam__bits: ['128', '64']

- name: edit debops inventory file
  lineinfile:
    path: /tmp/debops-test/ansible/inventory/hosts
    line: "{{ ansible_hostname }} ansible_host={{ ansible_hostname }} ansible_connection=local"

- name: run debops common on same container twice
  shell: "{{ item }}"
  args:
    chdir:
        /tmp/debops-test
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  with_items:
    - debops common
    - debops common
