---
# This actually fails with native Ansible 2.10; it hangs here in Azure tests:
# TASK [custom_python_new_style_module foo=True] *********************************
# task path: /home/vsts/work/1/s/tests/ansible/integration/runner/custom_python_new_style_module.yml:5
# Callback Exception: 
#   File "/tmp/venv/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 351, in send_callback
#     method(*new_args, **kwargs)
#    File "/tmp/venv/lib/python2.7/site-packages/ansible/plugins/callback/default.py", line 240, in v2_runner_on_start
#     if self.get_option('show_per_host_start'):
#    File "/tmp/venv/lib/python2.7/site-packages/ansible/plugins/callback/__init__.py", line 91, in get_option
#     return self._plugin_options[k]
# Using module file /home/vsts/work/1/s/tests/ansible/lib/modules/custom_python_new_style_module.py
# <localhost> ESTABLISH SSH CONNECTION FOR USER: mitogen__has_sudo_nopw
# <localhost> SSH: EXEC sshpass -d7 ssh -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 localhost '/bin/sh -c '"'"'echo ~mitogen__has_sudo_nopw && sleep 0'"'"''
# <localhost> (0, '/home/mitogen__has_sudo_nopw\n', '')
# <localhost> ESTABLISH SSH CONNECTION FOR USER: mitogen__has_sudo_nopw
# <localhost> SSH: EXEC sshpass -d7 ssh -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/mitogen__has_sudo_nopw/.ansible/tmp `"&& mkdir "` echo /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762 `" && echo ansible-tmp-1604117274.91-20588-59220641757762="` echo /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762 `" ) && sleep 0'"'"''
# <localhost> (0, 'ansible-tmp-1604117274.91-20588-59220641757762=/home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762\n', '')
# <localhost> PUT /home/vsts/.ansible/tmp/ansible-local-10393E_6qO3/tmpGnUAcy TO /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/AnsiballZ_custom_python_new_style_module.py
# <localhost> SSH: EXEC sshpass -d7 sftp -o BatchMode=no -b - -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 '[localhost]'
# <localhost> (0, 'sftp> put /home/vsts/.ansible/tmp/ansible-local-10393E_6qO3/tmpGnUAcy /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/AnsiballZ_custom_python_new_style_module.py\n', '')
# <localhost> PUT /home/vsts/.ansible/tmp/ansible-local-10393E_6qO3/tmpbf4OS4 TO /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/args
# <localhost> SSH: EXEC sshpass -d7 sftp -o BatchMode=no -b - -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 '[localhost]'
# <localhost> (0, 'sftp> put /home/vsts/.ansible/tmp/ansible-local-10393E_6qO3/tmpbf4OS4 /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/args\n', '')
# <localhost> ESTABLISH SSH CONNECTION FOR USER: mitogen__has_sudo_nopw
# <localhost> SSH: EXEC sshpass -d7 ssh -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 localhost '/bin/sh -c '"'"'chmod u+x /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/ /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/AnsiballZ_custom_python_new_style_module.py /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/args && sleep 0'"'"''
# <localhost> (0, '', '')
# <localhost> ESTABLISH SSH CONNECTION FOR USER: mitogen__has_sudo_nopw
# <localhost> SSH: EXEC sshpass -d7 ssh -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'User="mitogen__has_sudo_nopw"' -o ConnectTimeout=10 -o ControlPath=/home/vsts/.ansible/cp/6326e6fc14 -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/AnsiballZ_custom_python_new_style_module.py /home/mitogen__has_sudo_nopw/.ansible/tmp/ansible-tmp-1604117274.91-20588-59220641757762/args && sleep 0'"'"''
# but works just fine with Mitogen
# https://github.com/dw/mitogen/blob/master/tests/ansible/integration/runner/custom_python_new_style_module.yml#L1
# TEST=custom-python-new-style-module-ansible-2-10 make run-test
- custom_python_new_style_module:
    foo: true
  with_sequence: start=0 end={{end|default(1)}}
  register: out

- assert:
    that:
    - "not out.changed"
    - "not out.results[0].changed"
    # Random breaking interface change since 2.7.x
    #- "out.results[0].input[0].ANSIBLE_MODULE_ARGS.foo"
    - "out.results[0].msg == 'Here is my input'"

# Verify sys.argv is not Unicode.
- custom_python_detect_environment:
  register: out

- assert:
    that:
      - out.argv_types_correct
